CR
: require [compile] include ; immediate
[DEFINED] D<> [NOT] [IF] : D<> D= 0= ; [THEN]
[DEFINED] D>  [NOT] [IF] : D>  2SWAP D< ; [THEN]
[DEFINED] D>= [NOT] [IF] : D>= D< 0= ; [THEN]
[DEFINED] D<= [NOT] [IF] : D<= D> 0= ; [THEN]

[UNDEFINED] MAX-UINT [IF]
  [DEFINED] ENVIRONMENT [IF]
	ALSO ENVIRONMENT MAX-U CONSTANT MAX-UINT PREVIOUS
  [ELSE]
	-1 CONSTANT MAX-UINT
  [THEN]
[THEN]

[UNDEFINED] MIN-INT [IF]
  [DEFINED] ENVIRONMENT [IF]
	ALSO ENVIRONMENT MAX-N 1+ CONSTANT MIN-INT PREVIOUS
  [ELSE]
	0x80000000 CONSTANT MIN-INT
  [THEN]
[THEN]


include dbltest.fs
CR 



