\
\ test/environ.4th ---	prints, what ENVIRONMENT? reports.
\ (duz 05Aug93)
\

CR .( Environment as reported by system:)
CR .( ==================================)
CR

MARKER FORGET-ENVIRONMENT-DISPLAY
DECIMAL

: KNOWN?	2DUP TYPE 20 OUT @ - SPACES ." = "
		ENVIRONMENT? DUP 0= IF ." UNKNOWN!" CR  THEN ;

: .FLAG		KNOWN? IF  IF ." YES " ELSE ." NO " THEN  CR  THEN ;
: .NUMBER	KNOWN? IF  . CR  THEN ;

: SHOW-ENV	S" /COUNTED-STRING"	.NUMBER
		S" /HOLD"		.NUMBER
		S" /PAD"		.NUMBER
		S" ADDRESS-UNIT-BITS"	.NUMBER
		S" CORE"		.FLAG
		S" CORE-EXT"		.FLAG
		S" FLOORED"		.FLAG
		S" MAX-CHAR"		.NUMBER
		S" MAX-D"		KNOWN? IF  D. CR THEN
		S" MAX-N"		.NUMBER
		S" MAX-U"		KNOWN? IF  U. CR THEN
		S" MAX-UD"		KNOWN? IF UD. CR THEN
		S" RETURN-STACK-CELLS"	.NUMBER
		S" STACK-CELLS"		.NUMBER
		S" BLOCK"		.FLAG
		S" BLOCK-EXT"		.FLAG
		S" DOUBLE"		.FLAG
		S" DOUBLE-EXT"		.FLAG
		S" EXCEPTION"		.FLAG
		S" EXCEPTION-EXT"	.FLAG
		S" FACILITY"		.FLAG
		S" FACILITY-EXT"	.FLAG
		S" FILE"		.FLAG
		S" FILE-EXT"		.FLAG
		S" FLOATING"		.FLAG
		S" FLOATING-EXT"	.FLAG
		S" FLOATING-STACK"	.NUMBER
		S" MAX-FLOAT"		KNOWN? IF  FS. CR THEN
		S" LOCALS"		.FLAG
		S" LOCALS-EXT"		.FLAG
		S" #LOCALS"		.NUMBER
		S" MEMORY-ALLOC"	.FLAG
		S" MEMORY-ALLOC-EXT"	.FLAG
		S" TOOLS"		.FLAG
		S" TOOLS-EXT"		.FLAG
		S" SEARCH-ORDER"	.FLAG
		S" SEARCH-ORDER-EXT"	.FLAG
		S" WORDLISTS"		.NUMBER
		S" STRING"		.FLAG
		S" STRING-EXT"		.FLAG
		S" A NONSENSE STRING"	.FLAG
;

SHOW-ENV .S

FORGET-ENVIRONMENT-DISPLAY

CR

