EXTRA_DIST =  \
  anslocal.4th \
  anslocal.fs \
  anslocal.test64.ok \
  anslocal.test.ok \
  answords.fs \
  arith.4th \
  arith.sh \
  arith.test.ok \
  benchm.blk \
  bubble.fs \
  checkans.4th \
  checkans.fs \
  checkans.nomodules.ok \
  checkans.sh \
  checkans.test64.ok \
  checkans.test.ok \
  compare.4th \
  compare.sh \
  compare.test.ok \
  compspeed.fs \
  core.fr \
  coretest.4th \
  coretest.fs \
  coretest.sh \
  coretest.test.ok \
  dbltest.4th \
  dbltest.fs \
  deferred.fs \
  deferred-x.4th \
  deferred-x.fs \
  deferred-x.test64.ok \
  deferred-x.test.ok \
  defs.4th \
  defs.sh \
  defs.test.ok \
  dstester.fs \
  dstrings-test.fs \
  environ.4th \
  environ.nomodules.ok \
  environ.sh \
  environ.test64.ok \
  environ.test64W.ok \
  environ.test.ok \
  environ.testW.ok \
  exceptn.4th \
  exceptn.sh \
  exceptn.test.ok \
  fib.fs \
  file.4th \
  file.sh \
  file.test.ok \
  float.4th \
  float.nomodules.ok \
  float.sh \
  float.test64.ok \
  float.test.ok \
  forth-signal.4th \
  fpnostack.4th \
  fpnostack.nomodules.ok \
  fpnostack.sh \
  fpnostack.test64.ok \
  fpnostack.test.ok \
  fp-stack.4th \
  fp-stack.fs \
  fp-stack.nomodules.ok \
  fp-stack.test64.ok \
  fp-stack.test.ok \
  hashvocdistri.fs \
  intactv.4th \
  locals-ext.4th \
  loop-test.4th \
  loop-test.sh \
  loop-test.test.ok \
  matrix.fs \
  mini-oof.fs \
  moof-exm.fs \
  moofglos.fs \
  number-prefixes.4th \
  number-prefixes.fs \
  number-prefixes.test64.ok \
  number-prefixes.test.ok \
  parse-name.4th \
  parse-name.fs \
  parse-name.test64.ok \
  parse-name.test.ok \
  postpone.4th \
  postpone.fs \
  postpone.sh \
  postpone.test.ok \
  queryapp.4th \
  queryapp.sh \
  queryapp.test64.ok \
  queryapp.test.ok \
  run1.in.sh \
  search-order.4th \
  search-order.fs \
  search-order.sh \
  search-order.test.ok \
  sieve.fs \
  sievem.fs \
  siev.fs \
  sokoban.4th \
  sokoban.fs \
  speedwhile.fs \
  stack.4th \
  stack.sh \
  stack.test.ok \
  string.4th \
  string.sh \
  string.test.ok \
  suite.4th \
  tester.fr \
  tester.fs \
  test-num-prefixes2.4th \
  test-num-prefixes2.fs \
  test-num-prefixes2.test64.ok \
  test-num-prefixes2.test.ok \
  test-num-prefixes.4th \
  test-num-prefixes.fs \
  test-num-prefixes.test64.ok \
  test-num-prefixes.test.ok \
  trydstrings.fs \
  tt.4th \
  tt.fs \
  wordsets.4th \
  wordsets.fs \
  wordsets.nomodules.ok \
  wordsets.sh \
  wordsets.test.ok \
  $(NULL)
