#ifndef PFE_FACILITY_MIX_H
#define PFE_FACILITY_MIX_H 20091024
/* generated by make-header.py from ../../c/facility-mix.c */

#include <pfe/pfe-mix.h>

/**
 * -- Words making sense in POSIX-like systems only.
 *
 *  Copyright (C) Tektronix, Inc. 1998 - 2001.
 *  Copyright (C) 2005 - 2008 Guido U. Draheim <guidod@gmx.de>
 *
 *  @see     GNU LGPL
 *  @author  Guido U. Draheim            (modified by $Author: guidod $)
 *  @version $Revision: 522 $
 *     (modified $Date: 2009-10-24 00:11:48 +0200 (Sa, 24 Okt 2009) $)
 *
 *  @description
 *              This file exports a set of system words for
 *              a posixish OS environment. So should do
 *              any alternative wordset you might create for your OS.
 */

#ifdef __cplusplus
extern "C" {
#endif




/** #! ( "...<eol>" -- )
 * ignores the rest of the line,
 * defining `#!' is used to support forth scripts
 * executed by the unix kernel
 */
extern void FXCode (p4_ignore_line);

/** CLOCK@ ( --- clock-ticks# ) [EXT]
 * return clock(2) - the number of clocks of this process.
 * To get the number of seconds, divide by => CLOCKS_PER_SEC
 * as represented in the => ENVIROMENT for a hosted forth system.
 * A similar scheme is used by => MS@ to compute the clock time
 * rounded to milliseconds (named in similarity with => MS sleep).
 *
 * Remember that the process clock will wrap around at some point,
 * therefore only use difference values between two clock reads.
 *
 * OLD: this was also called CLOCK up to PFE 0.33.x
 */
extern void FXCode (p4_clock_fetch);

/** WFIELD: ( struct-sys offset "name" -- struct-sys offset+x )
 * The semantics of WFIELD: are identical to the execution
 * semantics of the phrase
  WCALIGNED /WCHAR +FIELD
 */
extern void FXCode (p4_w_field_colon);

/** WCHARS ( x -- x*y )
 * get address units occupied by a WCHAR (generally a 16bit entity)
 *
 * compare => /WCHAR and => CHARS
 */
extern void FXCode (p4_w_chars);

extern void FXCode_RT (p4_add_constant_RT);

/** +CONSTANT ( offset "name" -- )
 * create a new offsetword. The word is created and upon execution
 * it adds the offset, ie. compiling the => OFFSET-RT runtime:
       ( address -- address+offset )
 * This word is just a convenience word, just use the word => +FIELD
 * directly and choose a => DROP to flag the end of a current
 * offset-field declaration series.
 */
extern void FXCode (p4_add_constant);

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif
