double-sub.h : ../../c/double-sub.c ; ../../../tool/pfe/make-header.py $< $@
engine-sub.h : ../../c/engine-sub.c ; ../../../tool/pfe/make-header.py $< $@
engine-set.h : ../../c/engine-set.c ; ../../../tool/pfe/make-header.py $< $@
option-set.h : ../../c/option-set.c ; ../../../tool/pfe/make-header.py $< $@
block-sub.h : ../../c/block-sub.c ; ../../../tool/pfe/make-header.py $< $@
block-ext.h : ../../c/block-ext.c ; ../../../tool/pfe/make-header.py $< $@
block-mix.h : ../../c/block-mix.c ; ../../../tool/pfe/make-header.py $< $@
cdecl-ext.h : ../../c/cdecl-ext.c ; ../../../tool/pfe/make-header.py $< $@
chainlist-ext.h : ../../c/chainlist-ext.c ; ../../../tool/pfe/make-header.py $< $@
chain-ext.h : ../../c/chain-ext.c ; ../../../tool/pfe/make-header.py $< $@
core-sub.h : ../../c/core-sub.c ; ../../../tool/pfe/make-header.py $< $@
core-ext.h : ../../c/core-ext.c ; ../../../tool/pfe/make-header.py $< $@
core-mix.h : ../../c/core-mix.c ; ../../../tool/pfe/make-header.py $< $@
double-ext.h : ../../c/double-ext.c ; ../../../tool/pfe/make-header.py $< $@
double-mix.h : ../../c/double-mix.c ; ../../../tool/pfe/make-header.py $< $@
debug-ext.h : ../../c/debug-ext.c ; ../../../tool/pfe/make-header.py $< $@
dict-sub.h : ../../c/dict-sub.c ; ../../../tool/pfe/make-header.py $< $@
dict-comp.h : ../../c/dict-comp.c ; ../../../tool/pfe/make-header.py $< $@
dict-ext.h : ../../c/dict-ext.c ; ../../../tool/pfe/make-header.py $< $@
exception-sub.h : ../../c/exception-sub.c ; ../../../tool/pfe/make-header.py $< $@
exception-ext.h : ../../c/exception-ext.c ; ../../../tool/pfe/make-header.py $< $@
environ-ext.h : ../../c/environ-ext.c ; ../../../tool/pfe/make-header.py $< $@
facility-ext.h : ../../c/facility-ext.c ; ../../../tool/pfe/make-header.py $< $@
facility-mix.h : ../../c/facility-mix.c ; ../../../tool/pfe/make-header.py $< $@
file-ext.h : ../../c/file-ext.c ; ../../../tool/pfe/make-header.py $< $@
file-mix.h : ../../c/file-mix.c ; ../../../tool/pfe/make-header.py $< $@
file-sub.h : ../../c/file-sub.c ; ../../../tool/pfe/make-header.py $< $@
forth-83-ext.h : ../../c/forth-83-ext.c ; ../../../tool/pfe/make-header.py $< $@
forth-usual-ext.h : ../../c/forth-usual-ext.c ; ../../../tool/pfe/make-header.py $< $@
header-sub.h : ../../c/header-sub.c ; ../../../tool/pfe/make-header.py $< $@
header-ext.h : ../../c/header-ext.c ; ../../../tool/pfe/make-header.py $< $@
locals-ext.h : ../../c/locals-ext.c ; ../../../tool/pfe/make-header.py $< $@
memory-alloc-ext.h : ../../c/memory-alloc-ext.c ; ../../../tool/pfe/make-header.py $< $@
misc-ext.h : ../../c/misc-ext.c ; ../../../tool/pfe/make-header.py $< $@
option-ext.h : ../../c/option-ext.c ; ../../../tool/pfe/make-header.py $< $@
posix-ext.h : ../../c/posix-ext.c ; ../../../tool/pfe/make-header.py $< $@
search-order-ext.h : ../../c/search-order-ext.c ; ../../../tool/pfe/make-header.py $< $@
shell-os-ext.h : ../../c/shell-os-ext.c ; ../../../tool/pfe/make-header.py $< $@
signals-ext.h : ../../c/signals-ext.c ; ../../../tool/pfe/make-header.py $< $@
string-ext.h : ../../c/string-ext.c ; ../../../tool/pfe/make-header.py $< $@
system-ext.h : ../../c/system-ext.c ; ../../../tool/pfe/make-header.py $< $@
tools-sub.h : ../../c/tools-sub.c ; ../../../tool/pfe/make-header.py $< $@
tools-ext.h : ../../c/tools-ext.c ; ../../../tool/pfe/make-header.py $< $@
tools-mix.h : ../../c/tools-mix.c ; ../../../tool/pfe/make-header.py $< $@
term-ext.h : ../../c/term-ext.c ; ../../../tool/pfe/make-header.py $< $@
useful-ext.h : ../../c/useful-ext.c ; ../../../tool/pfe/make-header.py $< $@
your-ext.h : ../../c/your-ext.c ; ../../../tool/pfe/make-header.py $< $@
memory-sub.h : ../../c/memory-sub.c ; ../../../tool/pfe/make-header.py $< $@
version-sub.h : ../../c/version-sub.c ; ../../../tool/pfe/make-header.py $< $@
floating-ext.h : ../../c/floating-ext.c ; ../../../tool/pfe/make-header.py $< $@
floating-mix.h : ../../c/floating-mix.c ; ../../../tool/pfe/make-header.py $< $@
fpnostack-ext.h : ../../c/fpnostack-ext.c ; ../../../tool/pfe/make-header.py $< $@
complex-ext.h : ../../c/complex-ext.c ; ../../../tool/pfe/make-header.py $< $@
edit-ext.h : ../../c/edit-ext.c ; ../../../tool/pfe/make-header.py $< $@
help-ext.h : ../../c/help-ext.c ; ../../../tool/pfe/make-header.py $< $@
gforth-ext.h : ../../c/gforth-ext.c ; ../../../tool/pfe/make-header.py $< $@
assembler-ext.h : ../../c/assembler-ext.c ; ../../../tool/pfe/make-header.py $< $@
