#ifndef PFE_VERSION_SUB_H
#define PFE_VERSION_SUB_H 20091024
/* generated by make-header.py from ../../c/version-sub.c */

#include <pfe/pfe-sub.h>

/**
 * -- Version File
 *
 *  Copyright (C) Tektronix, Inc. 1998 - 2003.
 *  Copyright (C) 2005 - 2008 Guido U. Draheim <guidod@gmx.de>
 *
 *  @see     GNU LGPL
 *  @author  Guido U. Draheim            (modified by $Author: guidod $)
 *  @version $Revision: 514 $
 *     (modified $Date: 2009-10-22 16:18:28 +0200 (Do, 22. Okt 2009) $)
 *
 *  @description
 *      there are some internal functions in the version-file
 *      that are used to print out compile-time, -date, -version
 *      and the license of course.
 */

#ifdef __cplusplus
extern "C" {
#endif




/** PFE-VERSION */
extern P4_GCC_CONST const char* p4_version_string(void); /*{*/

/** PFE-COPYRIGHT */
extern P4_GCC_CONST const char* p4_copyright_string(void); /*{*/

/** PFE-LICENSE */
extern P4_GCC_CONST const char* p4_license_string (void); /*{*/

/** PFE-WARRANTY */
extern P4_GCC_CONST const char* p4_warranty_string (void); /*{*/

/** PFE-COMPILE-DATE */
extern P4_GCC_CONST const char* p4_compile_date (void); /*{*/

/** PFE-COMPILE-TIME */
extern P4_GCC_CONST const char* p4_compile_time (void); /*{*/

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif
