/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_plus_loop);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_dot_quote);
/*core-ext.c:*/ extern p4_Seman2 P4SEMANTICS (p4_semicolon);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_begin);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_do);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_does);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_else);
/*core-ext.c:*/ extern p4_Seman2 P4SEMANTICS (p4_exit);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_if);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_literal);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_loop);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_postpone);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_repeat);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_s_quote);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_then);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_until);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_while);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_bracket_tick);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_bracket_char);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_Q_do);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_again);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_c_quote);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_case);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_endcase);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_endof);
/*core-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_of);
/*core-ext.c:*/ extern p4_Seman2 P4SEMANTICS (p4_to);
/*double-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_two_literal);
/*dstrings-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_marg_execution);
/*dstrings-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_str_quote);
/*dstrings-ext.c:*/ extern p4_Semant P4SEMANTICS(p4_args_brace);
/*dstrings-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_m_quote);
/*dstrings-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_m_back_tick);
/*dstrings-ext.c:*/ extern p4_Semant P4SEMANTICS(p4_do_drop_str_frame);
/*exception-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_abort_quote);
/*floating-ext.c:*/ extern p4_Seman2 P4SEMANTICS (p4_f_literal);
/*forth-83-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_compile);
/*forth-83-ext.c:*/ extern p4_Semant P4SEMANTICS(p4_not);
/*forth-usual-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_ascii);
/*forth-usual-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_control);
/*header-ext.c:*/ extern p4_Semant P4SEMANTICS(p4_is);
/*locals-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_paren_local);
/*locals-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_locals_bar);
/*locals-ext.c:*/ extern p4_Seman2 P4SEMANTICS(p4_local_value);
/*misc-ext.c:*/ extern p4_Seman2 P4SEMANTICS (p4_plus_to);
/*misc-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_executes);
/*misc-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_load_quote);
/*misc-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_system_quote);
/*shell-os-ext.c:*/ //  extern p4_Semant P4SEMANTICS (P4CAT(p4_);
/*shell-os-ext.c:*/ //  extern p4_Semant P4SEMANTICS (P4CAT(p4_);
/*string-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_sliteral);
/*struct-ext.c:*/ extern p4_Semant P4SEMANTICS(p4_sizeof);
/*toolbelt-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_andif);
/*toolbelt-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_orif);
/*toolbelt-ext.c:*/ extern p4_Semant P4SEMANTICS(p4_tick_th);
/*useful-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_semicolon_and);
/*useful-ext.c:*/ extern p4_Seman2 P4SEMANTICS(p4_make);
/*useful-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_x_quote);
/*with-spy.c:*/ extern p4_Seman2 P4SEMANTICS (p4_spy_semicolon);
/*with-spy.c:*/ extern p4_Seman2 P4SEMANTICS (p4_spy_exit);
/*your-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_tick_from);
/*your-ext.c:*/ extern p4_Semant P4SEMANTICS (p4_fetch_from);
/*your-ext.c:*/ extern p4_Seman2 P4SEMANTICS (p4_into);
/*zchar-ext.c:*/ extern p4_Semant P4SEMANTICS(p4_z_quote);
/*zchar-ext.c:*/ extern p4_Semant P4SEMANTICS(p4_c_backslash_quote);
/*zchar-ext.c:*/ extern p4_Semant P4SEMANTICS(p4_s_backslash_quote);
/*zchar-ext.c:*/ extern p4_Semant P4SEMANTICS(p4_z_backslash_quote);
